import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Poppins } from "next/font/google";
import "../../globals.css";
import Header from "@/components/shared/header";
import Marquee from "@/components/ui/marquee";
import Footer from "@/components/shared/footer";
import Link from "next/link";
import Script from "next/script";
import GoogleAnalytics from "@/app/googleAnalytics";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children, params, modal }) {
  const [param, t] = await Promise.all([params, getTranslations("HomePage")]);

  // Validate the locale
  if (!routing.locales.includes(param.locale)) {
    notFound();
  }

  const wrapWithLink = (text, words, loc) => {
    const parts = text.split(new RegExp(`(${words.join("|")})`, "g"));
    return parts.map((part, index) =>
      words.includes(part) ? (
        <Link
          key={index}
          className="font-semibold inline"
          href={`/${param.locale}/${param.place}/sign-up`}
        >
          {part}
        </Link>
      ) : (
        part
      )
    );
  };

  const introText = wrapWithLink(
    t("intro"),
    ["Зарегистрируйтесь", "Register", "Hozir ro'yxatdan o'ting"],
    param.locale
  );

  // Retrieve messages for the specified locale
  const messages = await getMessages(param.locale);

  return (
    <html lang={param.locale}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=no"
        />
      </head>
      <body
        className={`${poppins.className} antialiased min-h-screen flex flex-col`}
      >
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-M3LDW3FG"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>

        {/* Google Analytics Script */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-PN4ZZXXGHP"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-PN4ZZXXGHP', {
              page_path: window.location.pathname,
            });
          `}
        </Script>

        {/* Google Tag Manager Script */}
        <Script id="gtm-init" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){
              w[l]=w[l]||[];
              w[l].push({'gtm.start': new Date().getTime(), event:'gtm.js'});
              var f=d.getElementsByTagName(s)[0],
                  j=d.createElement(s),
                  dl=l!='dataLayer'?'&l='+l:'';
              j.async=true;
              j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-M3LDW3FG');
          `}
        </Script>

        {/* Google Analytics Route Tracking */}
        <GoogleAnalytics />
        <NextIntlClientProvider locale={param.locale} messages={messages}>
          <Header />
          <div className="bg-secondary text-primary text-center">
            <div className="max-xl:block hidden max-sm:text-xs">
              <Marquee pauseOnHover className="[--duration:20s]">
                <p>{introText}</p>
              </Marquee>
            </div>
            <p className="hidden xl:block py-2">{introText}</p>
          </div>
          <main className="grow">
            {children}
            {modal}
          </main>
          {/* <Footer params={params} /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
