import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Poppins } from "next/font/google";
import "../../globals.css";
import Header from "@/components/shared/header";
import Marquee from "@/components/ui/marquee";
import Footer from "@/components/shared/footer";
import Link from "next/link";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children, params, modal }) {
  const [param, t] = await Promise.all([params, getTranslations("HomePage")]);

  // Validate the locale
  if (!routing.locales.includes(param.locale)) {
    notFound();
  }

  const wrapWithLink = (text, words, loc) => {
    const parts = text.split(new RegExp(`(${words.join("|")})`, "g"));
    return parts.map((part, index) =>
      words.includes(part) ? (
        <Link
          key={index}
          className="font-semibold inline"
          href={`/${param.locale}/${param.place}/sign-up`}
        >
          {part}
        </Link>
      ) : (
        part
      )
    );
  };

  const introText = wrapWithLink(
    t("intro"),
    ["Зарегистрируйтесь", "Register", "Hozir ro'yxatdan o'ting"],
    param.locale
  );

  // Retrieve messages for the specified locale
  const messages = await getMessages(param.locale);

  return (
    <html lang={param.locale}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=no"
        />
      </head>
      <body
        className={`${poppins.className} antialiased min-h-screen flex flex-col`}
      >
        <NextIntlClientProvider locale={param.locale} messages={messages}>
          <Header />
          <div className="bg-secondary text-primary text-center">
            <div className="max-xl:block hidden max-sm:text-xs">
              <Marquee pauseOnHover className="[--duration:20s]">
                <p>{introText}</p>
              </Marquee>
            </div>
            <p className="hidden xl:block py-2">{introText}</p>
          </div>
          <main className="grow">
            {children}
            {modal}
          </main>
          <Footer params={params} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
