import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { Link, routing } from "@/i18n/routing";
import { Poppins } from "next/font/google";
import "../../globals.css";
import Header from "@/components/shared/header";
import Marquee from "@/components/ui/marquee";
import Footer from "@/components/shared/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children, params }) {
  const [locale, t] = await Promise.all([params, getTranslations("HomePage")]);

  // Validate the locale
  if (!routing.locales.includes(locale.locale)) {
    notFound();
  }

  const wrapWithLink = (text, words, loc) => {
    const parts = text.split(new RegExp(`(${words.join("|")})`, "g"));
    return parts.map((part, index) =>
      words.includes(part) ? (
        <Link
          key={index}
          className="font-semibold inline"
          locale={loc}
          href="/sign-up"
        >
          {part}
        </Link>
      ) : (
        part
      )
    );
  };

  const introText = wrapWithLink(
    t("intro"),
    ["Зарегистрируйтесь", "Register", "Hozir ro'yxatdan o'ting"],
    locale.locale
  );

  // Retrieve messages for the specified locale
  const messages = await getMessages(locale.locale);

  return (
    <html lang={locale.locale}>
      <body
        className={`${poppins.className} antialiased min-h-screen flex flex-col`}
      >
        <NextIntlClientProvider locale={locale.locale} messages={messages}>
          <Header />
          <div className="bg-secondary text-primary text-center">
            <div className="max-xl:block hidden max-sm:text-xs">
              <Marquee pauseOnHover className="[--duration:20s]">
                <p>{introText}</p>
              </Marquee>
            </div>
            <p className="hidden xl:block py-2">{introText}</p>
          </div>
          <main className="grow mb-3">{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
